//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.28 at 11:10:31 AM CLST 
//


package edu.gemini.aspen.gmp.statusservice.osgi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChannelConfig" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="giapiname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="epicsname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="initial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "channelConfig"
})
@XmlRootElement(name = "Channels")
public class Channels {

    @XmlElement(name = "ChannelConfig", required = true)
    protected List<Channels.ChannelConfig> channelConfig;

    /**
     * Gets the value of the channelConfig property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channelConfig property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannelConfig().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Channels.ChannelConfig }
     * 
     * 
     */
    public List<Channels.ChannelConfig> getChannelConfig() {
        if (channelConfig == null) {
            channelConfig = new ArrayList<Channels.ChannelConfig>();
        }
        return this.channelConfig;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="giapiname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="epicsname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="initial" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "giapiname",
        "epicsname",
        "type",
        "initial"
    })
    public static class ChannelConfig {

        @XmlElement(required = true)
        protected String giapiname;
        @XmlElement(required = true)
        protected String epicsname;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String initial;

        /**
         * Gets the value of the giapiname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiapiname() {
            return giapiname;
        }

        /**
         * Sets the value of the giapiname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiapiname(String value) {
            this.giapiname = value;
        }

        /**
         * Gets the value of the epicsname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpicsname() {
            return epicsname;
        }

        /**
         * Sets the value of the epicsname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpicsname(String value) {
            this.epicsname = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the initial property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInitial() {
            return initial;
        }

        /**
         * Sets the value of the initial property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInitial(String value) {
            this.initial = value;
        }

    }

}
