#!/bin/bash
#
# description: Startup Script for all the instrument services.
#              It starts the GMP software and the Instrument 
#              software. It is intended to be used only "once"
#              as part of the initialization of the machine
#              after a reboot.
#
# NAME
#    gmp-full-start
#
# SYNOPSIS
#    gmp-full-start start
#
# DESCRIPTION
#    This is an init.d script used to start the GMP and the
#    instrument software once upon reboot. Once it is 
#    finished, this script deletes itself.  
#


# Source function library.
. /etc/init.d/functions


#start the GMP

start() {
    /etc/rc.d/init.d/gmp start
    /etc/rc.d/init.d/gpi start

    #remove myself from everywhere
    rm -f /etc/rc.d/rc3.d/S99gmp
    rm -f /etc/rc.d/rc5.d/S99gmp

}

# See how we were called.
case "$1" in
  start)
    start
    ;;
esac



